
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlv-static-config
  namespace: traefikee
data:
  static.yaml: |
    entryPoints:
      metrics:
        address: :8080
      web:
        address: :80
        transport:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        address: :443

    providers:
      kubernetesCRD: {}

    api:
      dashboard: true

    apiportal:
      path: spec.json

    metrics:
      prometheus:
        entryPoint: metrics

    log:
      level: DEBUG
      format: common
    accessLog:
      format: json
      filters: {}
      fields:
        defaultMode: keep
        headers:
          defaultMode: keep
          names:
            User-Agent: redact

    tracing:
      jaeger:
        samplingServerURL: http://jaeger-agent.jaeger:5778/sampling
        localAgentHostPort: jaeger-agent.jaeger:6831

    certificatesResolvers:
      default:
        acme:
          email: tee-prod@containo.us
          tlsChallenge: {}
      mypki:
        vault:
          url: http://vault.vault.svc.cluster.local:8200
          token: root
          role: enterprise-demo

    pilot:
      dashboard: false

    authSources:
      jwtSource:
        jwt:
          jwksUrl: https://keycloak.vlv.demo.traefiklabs.tech/auth/realms/traefiklabs/protocol/openid-connect/certs
      oidcSource:
        oidc:
          issuer: https://keycloak.vlv.demo.traefiklabs.tech/auth/realms/traefiklabs
          clientID: demo-app
          clientSecret: 37b7fec5-a64b-495a-a86a-303bb1e4819f

    cluster:
      cleanup:
        gracePeriod: 2m0s

    mesh:
      acl: true
      ignoreNamespaces:
      - traefikee
      - kube-system
      - default
      - monitoring
      defaultMode: http
      metrics:
        prometheus: {}