---
apiVersion: v1
kind: Namespace
metadata:
  name: vlv

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-server
  namespace: vlv

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-client
  namespace: vlv

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-client-noauth
  namespace: vlv

---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-client
  namespace: vlv
spec:
  serviceAccountName: app-client
  containers:
    - name: whoami-client
      image: giantswarm/tiny-tools:3.9
      command:
        - "sleep"
        - "3600"

---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-client-noauth
  namespace: vlv
spec:
  serviceAccountName: app-client-noauth
  containers:
    - name: whoami-client
      image: giantswarm/tiny-tools:3.9
      command:
        - "sleep"
        - "3600"